// 
// Code generated by Identity and Access VS Package
// 

using System.Globalization;
using System.Web.Mvc;
using FairlieAuthenticClientJWT.Models;

namespace FairlieAuthenticClientJWT.Controllers
{
    public class AccountController : Controller
    {
        [AllowAnonymous]
        public ActionResult Login()
        {
            ViewBag.MetaDataScript = "https://FairlieAuthentic.accesscontrol.windows.net/v2/metadata/identityProviders.js?protocol=wsfederation&realm=http://fairlieauthenticclient/&version=1.0&callback=ShowSigninPage";
            return View("~/Views/Account/Login.cshtml");
        }

        public ActionResult Index()
        {
            return View("Logout");
        }

        public void Logout()
        {
            string signoutUrl = new LogoutHandler().Signout();

            Response.Redirect(signoutUrl);
        }
    }
}
