// 
// Code generated by Identity and Access VS Package
// 

using System.Configuration;
using System.Globalization;
using System.Web.Mvc;
using FairlieAuthenticClientJWT.Models;

namespace FairlieAuthenticClientJWT.Controllers
{
    public class AccountController : Controller
    {
        [AllowAnonymous]
        public ActionResult Login()
        {
            ViewBag.MetaDataScript = ConfigurationManager.AppSettings["fa:LoginProviders"];
            return View("~/Views/Account/Login.cshtml");
        }
        
        [AllowAnonymous]
        public ActionResult Register()
        {
            ViewBag.role = "Not Authenticated";
            return View("Register");
        }

        public ActionResult Index()
        {
            return View("Logout");
        }

        public void Logout()
        {
            string signoutUrl = new LogoutHandler().Signout();

            Response.Redirect(signoutUrl);
        }
    }
}
